#references:
#https://stackoverflow.com/questions/26298821/django-testing-model-with-imagefield#26307916
#Consulted OpenAI ChatGPT-4 on chat.openai.com using the chat function.
#Link: https://chat.openai.com/
#Executed on a MacBook Air M1 8 cores (4p4e) 8GB RAM.
#Code generated by the model is preceded by #<BEGIN GENERATED model='gpt-4' date=2025-02-17>
#and followed by #<END GENERATED></END>.

from django.test import TestCase
from django.urls import reverse
from .models import Author
import uuid
from django.core.files.uploadedfile import SimpleUploadedFile


# Create your tests here.
class AuthorTests(TestCase):

    def setUp(self):
        #<BEGIN GENERATED model='gpt-4' date=2025-02-17 prompt: i want to write test code for my views.py functions but i need to set up an author first, here is a screenshot of my author model (screenshot of class Author from models.py), how do i upload an image for testing purposes?>
        self.image = SimpleUploadedFile("test_image.jpg", b"fake_image_data", content_type="image/jpeg")
        #<END GENERATED></END>
        self.author = Author.objects.create(
            username = "testuser",
            display_name = "Test User",
            github = "https://github.com/testuser",
            profile_image = self.image,
        )
    
    def test_get_author(self):
        response = self.client.get(reverse('get_author', args=[self.author.id]))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()['username'], "testuser")

    def test_update_author(self):
        response = self.client.post(reverse('update_author', args=[self.author.id]) , {
            "display_name":"Updated User",
            "github": "https://github.com/updateduser"
        }, content_type="application/json")
        self.assertEqual(response.status_code, 200)
        self.author.refresh_from_db()
        self.assertEqual(self.author.display_name, "Updated User")