services:
  web:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "[::]:8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "cd /app/salmon_project &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind [::]:8000 salmon_project.wsgi:application"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hello_django
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_django -d hello_django"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
