# Generated by Django 5.1.6 on 2025-03-30 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField(unique=True)),
                ('outgoing', models.BooleanField()),
                ('incoming', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('fqid', models.URLField(blank=True, editable=False, null=True, unique=True)),
                ('display_name', models.CharField(default='Display Name', max_length=100)),
                ('github', models.URLField(blank=True, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('page', models.URLField(blank=True, null=True)),
                ('host', models.URLField(default='http://127.0.0.1:8000')),
                ('is_approved', models.BooleanField(default=False)),
                ('following', models.ManyToManyField(blank=True, to='social_distribution.author')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='social_distribution.author')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(blank=True, editable=False, null=True, unique=True)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)'), ('application/base64', 'Base64 Data')], default='text/plain', max_length=100)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(blank=True, editable=False, null=True, unique=True)),
                ('comment', models.TextField()),
                ('content_type', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('fqid', models.URLField(blank=True, editable=False, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.comment')),
            ],
            options={
                'unique_together': {('object', 'author')},
            },
        ),
        migrations.CreateModel(
            name='FeedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='social_distribution.author')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_blocks', to='social_distribution.author')),
            ],
            options={
                'unique_together': {('blocker', 'blocked_author')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('fqid', models.URLField(blank=True, editable=False, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post')),
            ],
            options={
                'unique_together': {('object', 'author')},
            },
        ),
    ]
