# Generated by Django 5.1.1 on 2025-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://[2605:fd00:4:1001:f816:3eff:fe2c:1382]'),
        ),
    ]
