# Generated by Django 5.1.1 on 2025-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_alter_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000'),
        ),
    ]
