# Generated by Django 5.1.1 on 2025-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_alter_author_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)'), ('application/base64', 'Base64 Data')], default='text/plain', max_length=100),
        ),
    ]
