# Generated by Django 5.1.1 on 2025-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_alter_author_host_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
