# Generated by Django 5.1.6 on 2025-03-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_alter_author_host_alter_post_image'),
        ('social_distribution', '0003_remove_post_image_remove_post_text_remove_post_video_and_more'),
    ]

    operations = [
    ]
