# Generated by Django 5.1.1 on 2025-03-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_remotenode_password_remotenode_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
