# Generated by Django 5.1.1 on 2025-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://[2605:fd00:4:1001:f816:3eff:fe2c:1382]'),
        ),
    ]
