# Generated by Django 5.1.1 on 2025-03-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_remove_post_image_remove_post_text_remove_post_video_and_more'),
        ('social_distribution', '0004_alter_author_username'),
    ]

    operations = [
    ]
