# Generated by Django 5.1.6 on 2025-03-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_post_text_post_video_alter_author_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
