# Generated by Django 5.1.1 on 2025-03-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_merge_20250329_2315'),
        ('social_distribution', '0005_post_text_post_video_alter_author_host'),
    ]

    operations = [
    ]
