# Generated by Django 5.1.1 on 2025-03-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0006_merge_20250330_0017'),
        ('social_distribution', '0006_remove_post_image_remove_post_text_remove_post_video'),
    ]

    operations = [
    ]
