# Generated by Django 5.1.1 on 2025-02-20 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0006_followrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='social_distribution.author'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='social_distribution.author'),
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='accepted',
        ),
    ]
