# Generated by Django 5.1.6 on 2025-03-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0006_remove_post_image_remove_post_text_remove_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
