# Generated by Django 5.1.1 on 2025-03-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_merge_20250330_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
