# Generated by Django 5.1.1 on 2025-02-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_alter_followrequest_unique_together_and_more'),
        ('social_distribution', '0009_alter_post_video'),
    ]

    operations = [
    ]
