# Generated by Django 5.1.1 on 2025-02-22 01:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0009_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='created_at',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='created_at',
            new_name='published',
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('object', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('object', 'author')},
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
