# Generated by Django 5.1.1 on 2025-02-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_merge_20250222_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='social_distribution.author')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_blocks', to='social_distribution.author')),
            ],
            options={
                'unique_together': {('blocker', 'blocked_author')},
            },
        ),
    ]
