# Generated by Django 5.1.1 on 2025-02-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_merge_20250222_0240'),
        ('social_distribution', '0010_rename_text_comment_comment_and_more'),
    ]

    operations = [
    ]
