# Generated by Django 5.1.1 on 2025-02-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0011_feedblock'),
        ('social_distribution', '0011_merge_20250222_0633'),
    ]

    operations = [
    ]
