# Generated by Django 5.1.6 on 2025-03-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0012_merge_0011_feedblock_0011_merge_20250222_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, to='social_distribution.author'),
        ),
    ]
