# Generated by Django 5.1.1 on 2025-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0016_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fqid',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fqid',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
