# Generated by Django 5.1.1 on 2025-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0017_author_fqid_post_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fqid',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
