# Generated by Django 5.1.1 on 2025-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0018_comment_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='fqid',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='fqid',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
