# Generated by Django 5.1.1 on 2025-03-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0020_nodeinfo_remotenode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotenode',
            old_name='url',
            new_name='host',
        ),
    ]
