# Generated by Django 5.1.1 on 2025-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0021_rename_url_remotenode_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenode',
            name='incoming',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='outgoing',
            field=models.BooleanField(),
        ),
    ]
