# Generated by Django 5.1.1 on 2025-03-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0022_alter_remotenode_incoming_alter_remotenode_outgoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeinfo',
            name='host',
            field=models.URLField(unique=True),
        ),
    ]
