name: ci 
on:
  push:
    branches:
      - main
      - development
      - development-s2
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        # Set up Python environment for Django
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.x

        # Install Python dependencies
        - name: Install dependencies
          working-directory: src/salmon_project
          run: pip install -r requirements.txt
        
        # Run Django tests
        - name: Run Django tests
          working-directory: src/salmon_project
          run: python manage.py test